"""NODEMAP_REPORT.md: the one-page, LLM-friendly map of a Godot project."""
from __future__ import annotations

from collections import Counter
from pathlib import PurePosixPath

from . import analyze
from .graph import Graph
from .query import _short, fmt_edge, fmt_loc, scene_tree


def generate(g: Graph, max_issues: int = 25, max_tree_nodes: int = 40) -> str:
    m = g.meta
    st = analyze.stats(g)
    gods = analyze.god_nodes(g)
    bus = analyze.signal_bus(g)
    surprising = analyze.surprising_connections(g)
    L: list[str] = []
    title = m.get("project") or PurePosixPath(m.get("root", "")).name
    L.append(f"# NODEMAP REPORT: {title}")
    L.append("")
    feats = ", ".join(m.get("engine_features", []))
    L.append(f"Godot {feats or '4.x'} | renderer: {m.get('renderer') or 'default'} | "
             f"{'GDScript + C#' if m.get('csharp') else 'GDScript'} | "
             f"{m['files']['scripts']} scripts, {m['files']['scenes']} scenes, {m['files']['resources']} resources")
    L.append(f"Graph: {st['nodes']} nodes, {st['edges']} edges, {st['communities']} communities | "
             f"edges: " + ", ".join(f"{k} {v}" for k, v in st["confidence"].items()))
    L.append("")
    L.append("> Generated by godot-nodemap. Query it instead of grepping: `nodemap query \"...\"`, "
             "`nodemap explain X`, `nodemap tree Scene`, `nodemap signal name`, `nodemap check`.")
    L.append("")

    # ---------------------------------------------------------------- project
    L.append("## Project map")
    L.append("")
    if m.get("main_scene"):
        L.append(f"- **Main scene:** `{m['main_scene']}`")
    if m.get("plugins"):
        L.append(f"- **Editor plugins:** {', '.join(m['plugins'])}")
    L.append("")
    if m.get("autoloads"):
        L.append("### Autoloads (global singletons, access by name from any script)")
        L.append("")
        L.append("| Name | File | Used by | Signals |")
        L.append("|---|---|---|---|")
        used_by = Counter(e["target"] for e in g.edges if e["relation"] == "uses_autoload")
        for name, path in m["autoloads"].items():
            sigs = [n["label"] for n in g.nodes.values() if n["kind"] == "signal" and n.get("script") == path]
            L.append(f"| `{name}` | `{path.replace('res://', '')}` | {used_by.get('autoload:' + name, 0)} scripts | "
                     f"{', '.join(sigs[:8])}{' ...' if len(sigs) > 8 else ''} |")
        L.append("")
    actions = [n for n in g.nodes.values() if n["kind"] == "action"]
    if actions:
        used = Counter(e["target"] for e in g.edges if e["relation"] == "uses_action")
        L.append("### Input actions")
        L.append("")
        for a in sorted(actions, key=lambda a: a["label"]):
            where = "built-in" if a.get("builtin") else a.get("declared_in", "")
            L.append(f"- `{a['label']}` ({where}, used {used.get(a['id'], 0)}x)")
        L.append("")
    groups = [n for n in g.nodes.values() if n["kind"] == "group"]
    if groups:
        L.append("### Groups")
        L.append("")
        mem = Counter(e["target"] for e in g.edges if e["relation"] in ("in_group", "adds_to_group"))
        q = Counter(e["target"] for e in g.edges if e["relation"] == "queries_group")
        L.append(", ".join(f"`{n['label']}` (+{mem.get(n['id'], 0)}/?{q.get(n['id'], 0)})"
                           for n in sorted(groups, key=lambda n: n["label"])))
        L.append("")
    if m.get("layer_names"):
        L.append("### Named layers")
        L.append("")
        L.append(", ".join(f"{k}=`{v}`" for k, v in m["layer_names"].items()))
        L.append("")

    # ---------------------------------------------------------------- health
    sev = Counter(i["severity"] for i in g.issues)
    L.append("## Health check")
    L.append("")
    L.append(f"{sev.get('error', 0)} errors, {sev.get('warning', 0)} warnings, {sev.get('info', 0)} notes. "
             "Run `nodemap check` for the full list.")
    L.append("")
    for level in ("error", "warning"):
        items = [i for i in g.issues if i["severity"] == level]
        if not items:
            continue
        L.append(f"**{level}s**")
        L.append("")
        for i in items[:max_issues]:
            L.append(f"- `{fmt_loc(file=i['file'], line=i['line'])}` {i['code']}: {i['message']}")
        if len(items) > max_issues:
            L.append(f"- ... {len(items) - max_issues} more")
        L.append("")

    # ---------------------------------------------------------------- god nodes
    L.append("## God nodes (most connected across files)")
    L.append("")
    for nid, d in gods:
        n = g.nodes[nid]
        L.append(f"- **{_short(g, nid)}** [{n['kind']}] touched by {d} files ({fmt_loc(n)})")
    L.append("")

    # ---------------------------------------------------------------- communities
    L.append("## Communities (subsystems)")
    L.append("")
    deg = analyze.degree_table(g)
    for cid, members in sorted(g.communities.items(), key=lambda kv: -len(kv[1]))[:20]:
        files = [x for x in members if g.nodes[x]["kind"] in ("script", "scene", "resource", "autoload")]
        if not files:
            continue
        top = sorted(files, key=lambda x: (analyze.is_test(g.nodes[x].get("file", x)), -deg.get(x, 0)))[:8]
        L.append(f"- **C{cid}: {g.community_labels.get(cid, '')}** ({len(files)} files): "
                 + ", ".join(_short(g, t) for t in top))
    L.append("")

    # ---------------------------------------------------------------- signals
    if bus:
        L.append("## Signal bus")
        L.append("")
        L.append("| Signal | Declared in | Emitted by | Listened by |")
        L.append("|---|---|---|---|")
        for s in bus[:30]:
            em = _owners(g, s["emitters"])
            li = _owners(g, s["listeners"])
            L.append(f"| `{s['name']}({s['params']})` | {_short(g, s['script'])} | {em} | {li} |")
        if len(bus) > 30:
            L.append(f"\n... {len(bus) - 30} more signals (`nodemap signal <name>`)")
        L.append("")

    # ---------------------------------------------------------------- scenes
    scenes = [n for n in g.nodes.values() if n["kind"] == "scene" and not n.get("external")]
    if scenes:
        L.append("## Scenes")
        L.append("")
        for s in sorted(scenes, key=lambda s: (not s.get("main_scene"), s["id"])):
            tree = scene_tree(g, s["id"]).splitlines()
            L.append("```")
            L.extend(tree[: max_tree_nodes + 1])
            if len(tree) > max_tree_nodes + 1:
                L.append(f"... {len(tree) - max_tree_nodes - 1} more nodes (nodemap tree {s['label']})")
            L.append("```")
        L.append("")

    # ---------------------------------------------------------------- surprising
    if surprising:
        L.append("## Surprising connections (links between subsystems that rarely talk)")
        L.append("")
        for e in surprising:
            L.append(f"- {fmt_edge(g, e)}")
        L.append("")

    L.append("## Suggested questions")
    L.append("")
    for q in analyze.suggest_questions(g, gods, bus):
        L.append(f"- {q}")
    L.append("")
    return "\n".join(L)


def _owners(g: Graph, ids: list[str], limit: int = 4) -> str:
    """Distinct owning scripts, game code before tests."""
    owners = {}
    for x in ids:
        owners.setdefault(_short(g, x).split(".")[0], g.nodes.get(x, {}).get("file", ""))
    names = sorted(owners, key=lambda o: (analyze.is_test(owners[o]), o))
    txt = ", ".join(names[:limit])
    if len(names) > limit:
        txt += f" +{len(names) - limit}"
    return txt or "-"
